# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run coverage
      - store_artifacts:
          path: test-results.xml
          destination: test-results
      - store_artifacts:
          path: coverage
          destination: coverage